Ignore pull failures

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -16,7 +16,11 @@ jobs:
         uses: harvard-lil/docker-compose-update-action@main
 
       - name: docker compose up
-        run: docker compose -f docker-compose.yml up -d
+        run:
+          # --ignore-pull-failures for PRs with new images
+          # that haven't been pushed yet:
+          docker-compose -f docker-compose.yml pull --ignore-pull-failures || true
+          docker compose -f docker-compose.yml up -d
 
       - name: Show running containers
         run: docker ps -a
